# Generated by Django 4.2.3 on 2023-08-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeM',
            fields=[
                ('emp_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
